<a href="https://colab.research.google.com/github/asmi2604/nps-score-analysis/blob/main/NPS_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Importing Libraries

In [ ]:
import numpy as np
url = "https://drive.google.com/uc?export=download&id=1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK"
score = np.loadtxt(url)
print(score)

[ 7. 10.  5. ...  5.  9. 10.]


####Q1. What NumPy technique is used to filter scores where respondents are detractors (score≤6)?


In [ ]:
score

array([ 7., 10.,  5., ...,  5.,  9., 10.])

In [ ]:
score<=6

array([False, False,  True, ...,  True, False, False])

In [ ]:
score[score<=6]

array([5., 4., 4., 5., 1., 5., 5., 1., 4., 5., 4., 4., 4., 5., 1., 4., 1.,
       4., 1., 5., 5., 1., 1., 4., 1., 5., 4., 1., 1., 4., 1., 5., 1., 4.,
       4., 1., 1., 1., 1., 1., 1., 1., 4., 1., 1., 5., 5., 5., 4., 4., 1.,
       4., 1., 4., 1., 5., 1., 1., 5., 4., 4., 4., 4., 1., 4., 5., 4., 4.,
       1., 1., 5., 5., 1., 5., 1., 5., 5., 4., 5., 4., 1., 1., 1., 1., 4.,
       1., 4., 4., 5., 4., 1., 1., 1., 1., 5., 4., 5., 5., 4., 1., 5., 1.,
       4., 4., 1., 1., 1., 4., 4., 5., 5., 4., 5., 5., 5., 1., 4., 1., 5.,
       5., 1., 5., 1., 1., 5., 5., 4., 4., 1., 4., 4., 4., 1., 1., 4., 4.,
       4., 5., 5., 1., 1., 4., 1., 4., 1., 4., 1., 4., 1., 4., 1., 5., 4.,
       4., 5., 1., 4., 5., 5., 5., 1., 5., 4., 1., 1., 5., 5., 5., 4., 5.,
       4., 4., 1., 4., 4., 4., 4., 5., 1., 5., 5., 1., 4., 4., 5., 1., 1.,
       4., 5., 5., 5., 1., 4., 5., 5., 4., 1., 5., 5., 5., 1., 1., 5., 5.,
       1., 1., 1., 4., 5., 5., 4., 4., 4., 5., 1., 4., 1., 4., 5., 4., 5.,
       5., 1., 5., 1., 5.

In [ ]:
score[score<=6].shape[0]

332

In [ ]:
promoters = score[score >= 9]
# Number of promoters-
num_promoters = len(promoters)
num_promoters

609

In [ ]:
detractors = score[score <= 6]
# Number of detractors-
num_detractors = len(detractors)
num_detractors

332

In [ ]:
score.shape[0]

1167

####Q2. Calculate the percentage of Promoters (where score≥9) from the NumPy array score?

In [ ]:
total= score.shape[0]

In [ ]:
percentage_promoters = (num_promoters/total) * 100
percentage_promoters

52.185089974293064

####Question 3: What does this line of code calculate?                       NPS = percentage_promoters - percentage_detractors

In [ ]:
percentage_promoters

52.185089974293064

In [ ]:
percentage_detractors = (num_detractors/total) * 100
percentage_detractors

28.449014567266495

In [ ]:
NPS = percentage_promoters - percentage_detractors
NPS

23.73607540702657

## Use Case: Fitness data analysis

In [ ]:
data = np.loadtxt("fit.txt",dtype = "str")
print(data)

[['06-10-2017' '5464' 'Neutral' '181' '5' 'Inactive']
 ['07-10-2017' '6041' 'Sad' '197' '8' 'Inactive']
 ['08-10-2017' '25' 'Sad' '0' '5' 'Inactive']
 ['09-10-2017' '5461' 'Sad' '174' '4' 'Inactive']
 ['10-10-2017' '6915' 'Neutral' '223' '5' 'Active']
 ['11-10-2017' '4545' 'Sad' '149' '6' 'Inactive']
 ['12-10-2017' '4340' 'Sad' '140' '6' 'Inactive']
 ['13-10-2017' '1230' 'Sad' '38' '7' 'Inactive']
 ['14-10-2017' '61' 'Sad' '1' '5' 'Inactive']
 ['15-10-2017' '1258' 'Sad' '40' '6' 'Inactive']
 ['16-10-2017' '3148' 'Sad' '101' '8' 'Inactive']
 ['17-10-2017' '4687' 'Sad' '152' '5' 'Inactive']
 ['18-10-2017' '4732' 'Happy' '150' '6' 'Active']
 ['19-10-2017' '3519' 'Sad' '113' '7' 'Inactive']
 ['20-10-2017' '1580' 'Sad' '49' '5' 'Inactive']
 ['21-10-2017' '2822' 'Sad' '86' '6' 'Inactive']
 ['22-10-2017' '181' 'Sad' '6' '8' 'Inactive']
 ['23-10-2017' '3158' 'Neutral' '99' '5' 'Inactive']
 ['24-10-2017' '4383' 'Neutral' '143' '4' 'Inactive']
 ['25-10-2017' '3881' 'Neutral' '125' '5' 'Inactive'

/tmp/ipython-input-4200134561.py:1: UserWarning: Input line 1 contained no data and will not be counted towards `max_rows=50000`.  This differs from the behaviour in NumPy <=1.22 which counted lines rather than rows.  If desired, the previous behaviour can be achieved by using `itertools.islice`.
Please see the 1.23 release notes for an example on how to do this.  If you wish to ignore this warning, use `warnings.filterwarnings`.  This warning is expected to be removed in the future and is given only once per `loadtxt` call.
  data = np.loadtxt("fit.txt",dtype = "str")


In [ ]:
step_count = data[:, 1].astype(int)
mood = data[:, 2]
calories = data[:, 3].astype(int)
sleep = data[:, 4].astype(int)
activity = data[:, 5]

In [ ]:
mood

array(['Neutral', 'Sad', 'Sad', 'Sad', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Sad', 'Sad', 'Sad', 'Happy', 'Sad', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral', 'Neutral',
       'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Neutral',
       'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Neutral', 'Sad', 'Happy', 'Happy', 'Happy',
       'Happy', 'Happy', 'Happy', 'Happy', 'Sad', 'Neutral', 'Neutral',
       'Sad', 'Sad', 'Neutral', 'Neutral', 'Happy', 'Neutral', 'Neutral',
       'Sad', 'Neutral', 'Sad', 'Neutral', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Sad', 'Happy', 'Neutral', 'Happy', 'Neutral', 'Sad', 'Sad', 'Sad',
       'Neutral', 'Neutral', 'Sad', 'Sad', 'Happy', 'Neutral', 'Neutral',
       'Happy'], dtype='<U10')

In [ ]:
step_count

array([5464, 6041,   25, 5461, 6915, 4545, 4340, 1230,   61, 1258, 3148,
       4687, 4732, 3519, 1580, 2822,  181, 3158, 4383, 3881, 4037,  202,
        292,  330, 2209, 4550, 4435, 4779, 1831, 2255,  539, 5464, 6041,
       4068, 4683, 4033, 6314,  614, 3149, 4005, 4880, 4136,  705,  570,
        269, 4275, 5999, 4421, 6930, 5195,  546,  493,  995, 1163, 6676,
       3608,  774, 1421, 4064, 2725, 5934, 1867, 3721, 2374, 2909, 1648,
        799, 7102, 3941, 7422,  437, 1231, 1696, 4921,  221, 6500, 3575,
       4061,  651,  753,  518, 5537, 4108, 5376, 3066,  177,   36,  299,
       1447, 2599,  702,  133,  153,  500, 2127, 2203])

#####Question 4: What is the average step count on "Active" days?

In [ ]:
activity == "Active"

array([False, False, False, False,  True, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False,  True, False,
       False, False, False,  True, False, False, False, False, False,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False, False, False, False, False, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
       False,  True,  True, False,  True,  True,  True,  True,  True,
       False,  True,  True,  True,  True, False, False, False, False,
        True,  True,  True,  True, False, False, False, False, False,
       False, False, False,  True, False,  True])

In [ ]:
step_count[activity == "Active"]

array([6915, 4732, 4550,  539, 6314,  614, 3149, 4005, 4880, 4136,  705,
        570,  269,  493,  995, 1163, 6676, 3608,  774, 1421, 4064, 2725,
       5934, 1867, 3721, 2909, 1648, 7102, 3941, 7422,  437, 1231, 4921,
        221, 6500, 3575, 5537, 4108, 5376, 3066,  500, 2203])

In [ ]:
np.mean(step_count[activity == "Active"])

np.float64(3226.5714285714284)

####Q5. How many days had more than 5000 steps and burned more than 150 calories?

In [ ]:
(step_count > 5000) & (calories>150)

array([ True,  True, False,  True,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True, False, False, False,
        True, False, False, False, False, False, False, False, False,
       False,  True, False,  True,  True, False, False, False, False,
        True, False, False, False, False, False,  True, False, False,
       False, False, False, False,  True, False,  True, False, False,
       False, False, False,  True, False, False, False, False, False,
        True, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False])

In [ ]:
True + True +False

2

In [ ]:
np.sum([True,False,True])

np.int64(2)

In [ ]:
np.sum((step_count > 5000) & (calories>150))

np.int64(17)

####Q6. What percentage of days had a "Sad" mood?

In [ ]:
np.sum(mood == 'Sad') /len(mood)

np.float64(0.3020833333333333)

In [ ]:
(np.sum(mood == 'Sad') /len(mood))  * 100

np.float64(30.208333333333332)

####Q7. What is the maximum number of steps taken on days with less than 6 hours of sleep?

In [ ]:
np.max(step_count[sleep<6])

np.int64(7422)

####Q8. What are the average calories burned per hour of sleep on "Inactive" days?

In [ ]:
calories[activity == 'Inactive'] / sleep[activity == 'Inactive']

array([36.2       , 24.625     ,  0.        , 43.5       , 24.83333333,
       23.33333333,  5.42857143,  0.2       ,  6.66666667, 12.625     ,
       30.4       , 16.14285714,  9.8       , 14.33333333,  0.75      ,
       19.8       , 35.75      , 25.        , 21.5       ,  0.75      ,
        1.8       ,  1.66666667, 14.4       , 28.2       , 39.        ,
       11.4       , 18.        , 45.25      , 65.66666667, 65.5       ,
       17.11111111, 27.4       , 29.        , 32.        , 29.2       ,
       39.        , 33.4       ,  2.66666667, 19.        ,  6.25      ,
       13.75      , 25.8       ,  4.2       ,  7.        ,  5.33333333,
        1.        ,  0.33333333,  3.33333333, 15.66666667, 42.        ,
        7.66666667,  2.        ,  0.        ,  0.        ])

In [ ]:
np.mean(calories[activity == 'Inactive'] / sleep[activity == 'Inactive']
)

np.float64(18.62282480893592)